config/routes.rb
Rails.application.routes.draw do
  # todo(todolist)を作成
  get  'todolist/new',    to: 'todolist#new',    as: 'new_todolist'
  post 'todolist/create', to: 'todolist#create', as: 'create_todolist'

  #todoを参照
  get 'todolist/:id',     to: 'todolist#todoshow'  ,as: 'todo'
  get 'todolist/users/:id', to: 'todolist#usertodoshow'

  #todoを更新
  get 'todolist/:id/edit',to: 'todolist#edit'
  patch 'todolist/:id',   to: 'todolist#update'     ,as: 'update_todolist'

  #todoを削除
  delete 'todo/:id',       to: 'todolist#delete'    ,as: 'tododelete'
  delete 'todolist/:id',   to: 'todolist#listdelete',as: 'listdelete_todolist'

  #todostate(todoを追加)
  get  'todostates/new',    to: 'todostates#new'
  post 'todostates/create', to: 'todostates#create', as: 'add_todo'

  #todoの状況を参照
  get 'todostates/:id',     to: 'todostates#show',as: 'todostate'

  #todoの状況を更新
  patch 'todostates/:id',     to: 'todostates#update', as: 'update_status'

  root 'maps#index'
  get  '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # commentを作成
  get  'comments/new',      to: 'comments#new', as: 'new_comment'
  post 'comments/create',   to: 'comments#create', as: 'create_comment'

  #　commentを参照
  get  'comments/:id',      to: 'comments#show', as: 'comment'

  # commentを更新
  get  'comments/:id/edit', to: 'comments#edit', as: 'edit_comment'
  patch 'comments/:id',     to: 'comments#update', as: 'update_comment'

  # commentを削除
  delete 'comments/:id',    to: 'comments#destroy', as: 'destroy_comment'
end

app/models/todolist.rb
class Todolist < ApplicationRecord
  belongs_to :todo
  has_many :todostates
  #不要なため削除
  # belongs_to :user
  #一つの投稿に対して、一つの画像をUPLOAD可能
  has_one_attached :image, dependent: :destroy
  #画像に対するバリデーション
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                                  size:         { less_than: 5.megabytes,
                                    message:   "should be less than 5MB" }
end

app/controllers/todolist_controller.rb
class TodolistController < ApplicationController
  before_action :require_login, only: %i[new create edit update delete listdelete]

  # 新しいtodoとtodolistを作成
  def new
    @todo = Todo.new
    @todo.todo_lists.build
  end

  # todo(todolist)を登録
  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to root_path
    else
      render :new
    end
  end

  # 各todolistの詳細を参照
  def todoshow
    @todo = Todo.includes(:todo_lists).find(params[:id])
    @todo_lists = @todo.todo_lists

    @image_urls = @todo_lists.map do |todolist|
      url_for(todolist.image) if todolist.image.attached?
    end.compact
  end

  # ユーザーが作成したTodoをすべて参照
  def usertodoshow
    @todo = Todo.includes(:todo_lists).where(user_id: params[:id])

    @todo_lists = @todo.todo_lists

    @image_urls = @todo_lists.map do |todolist|
      url_for(todolist.image) if todolist.image.attached?
    end.compact
  end

  # Todolistの更新
  def edit
    @todo = Todo.includes(:todo_lists).find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    # 更新のTodolistとログイン中にユーザを比較
    return unless @todo.user_id == @current_user.id

    # 一致していれば、更新
    if @todo.update(todo_params)
      redirect_to todo_path(@todo)
    # 更新できない場合
    else
      render :edit
    end
  end

  # Todolistの削除
  def delete
    @todo = Todo.find(params[:id])
    return unless @todo.user_id == @current_user.id

    @todo.destroy
    redirect_to root_path
  end

  def listdelete
    @todolist = Todolist.find(params[:id])
    @todo = Todo.find(@todolist.todo_id)

    return unless @todo.user_id == @current_user.id

    @todolist.destroy
    redirect_to todo_path(@todo)
  end

  private

  # パラメータ制御
  def todo_params
    params.require(:todo).permit(:id, :title, :description, :user_id,
                                 todo_lists_attributes: %i[id latitude longitude details image])
  end

  # ログインが必要
  def require_login
    redirect_to login_path, alert: 'Please log in to continue' unless logged_in?
  end
end

app/helpers/todolist_helper.rb
module TodolistHelper
end

app/views/todolist/edit.html.erb
<%= form_with(model: @todo, local: true, url: update_todolist_path(@todo), method: :patch) do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.hidden_field :user_id, value: @current_user.id %>
  </div>

  <% @todo.todo_lists.each_with_index do |todo_list, index| %>
    <h3>Set <%= index + 1 %></h3>
    <%= f.fields_for :todo_lists, todo_list do |tf| %>
      <div>
        <%= tf.label :latitude %>
        <%= tf.text_field :latitude %>
      </div>

      <div>
        <%= tf.label :longitude %>
        <%= tf.text_field :longitude %>
      </div>

      <div>
        <%= tf.label :details %>
        <%= tf.text_area :details %>
      </div>

      <div>
        <%= tf.label :image %>
        <%= tf.file_field :image %>
      </div>
    <% end %>
  <% end %>

  <div>
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= form_with(url: tododelete_path(@todo), method: :delete, local: true) do %>
  <%= submit_tag 'Delete Todo' %>
<% end %>

<% @todo.todo_lists.each_with_index do |todo_list, index| %>
  <h3>Set <%= index + 1 %></h3>
  <div>
    <%= index %>
  </div>
  <%= form_with(url: listdelete_todolist_path(todo_list), method: :delete, local: true) do %>
    <%= submit_tag 'Delete Todolist' %>
  <% end %>      
<% end %>

app/views/todolist/new.html.erb
<%= form_with(model: @todo, local: true, url: create_todolist_path) do |f| %>
<div>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
</div>  

  <div>
    <%= f.hidden_field :user_id, value: @current_user.id %>
  </div>

  <% (1..3).each do |index| %>
    <h3>Set <%= index %></h3>
    <%= f.fields_for :todo_lists, @todo.todo_lists[index] || @todo.todo_lists.build do |tf| %>
      <div>
        <%= tf.label :latitude %>
        <%= tf.text_field :latitude %>
      </div>

      <div>
        <%= tf.label :longitude %>
        <%= tf.text_field :longitude %>
      </div>

      <div>
        <%= tf.label :details %>
        <%= tf.text_area :details %>
      </div>

      <div>
        <%= tf.label :image %>
        <%= tf.file_field :image %>
      </div>
    <% end %>
  <% end %>

  <div>
    <%= f.submit "Create Todo" %>
  </div>
<% end %>

app/views/todolist/todoshow.html.erb
<h1>Todo Details</h1>

<div>
  <strong>Title:</strong>
  <h2><%= @todo.title %></h2>
</div>

<div>
  <strong>Description:</strong>
  <h2><%= @todo.description %></h2>
</div>

<% @todo.todo_lists.each_with_index do |todo_list, outer_index| %>
  <div>
    <h1><%= outer_index+1 %></h1>
    <strong>Latitude:</strong>
    <p><%= todo_list.latitude %></p>
  </div>
  <div>
    <strong>Longitude:</strong>
    <p><%= todo_list.longitude %></p>
  </div>
  <div>
    <strong>Details:</strong>
    <p><%= todo_list.details %></p>
  </div>
<% end %>

<h2>Comments</h2>

<% if logged_in? %>
  <div>
    <%= form_with(model: [@todo, @todo.comments.build], local: true) do |form| %>
      <div class="form-group">
        <%= form.label :comment %>
        <%= form.text_area :comment, class: "form-control", rows: 3 %>
      </div>
      <div class="form-group">
        <%= form.submit "Post Comment", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Please <a href="<%= login_path %>">log in</a> to post a comment.</p>
<% end %>

<h3>Existing Comments</h3>
<% @todo.comments.each do |comment| %>
  <div>
    <strong><%= comment.user.name %>:</strong>
    <p><%= comment.comment %></p>
    <p><small><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></small></p>
  </div>
<% end %>

app/views/todolist/usertodoshow.html.erb
<% @todo.each_with_index do |todo, index| %>
  <div>
      <h1>Todo Details<%= index%></h1>
        <div>
          <strong>Title:</strong>
          <h2><%= todo.title %></h2>
        </div>

        <div>
          <strong>Description:</strong>
          <h2><%= todo.description %></h2>
        </div>

        <h3>Todo Lists:</h3>
        <% todo.todo_lists.each do |todo_list ,index| %>
          <div>
            <strong>Latitude:</strong>
            <p><%= todo_list.latitude %></p>
          </div>
          <div>
            <strong>Longitude:</strong>
            <p><%= todo_list.longitude %></p>
          </div>
          <div>
            <strong>Details:</strong>
            <p><%= todo_list.details %></p>
          </div>
  </div>

  <% end %>
<% end %>