config/routes.rb
Rails.application.routes.draw do
  # todo(todolist)を作成
  get  'todolist/new',    to: 'todolist#new',    as: 'new_todolist'
  post 'todolist/create', to: 'todolist#create', as: 'create_todolist'

  #todoを参照
  get 'todolist/:id',     to: 'todolist#todoshow'  ,as: 'todo'
  get 'todolist/users/:id', to: 'todolist#usertodoshow'

  #todoを更新
  get 'todolist/:id/edit',to: 'todolist#edit'
  patch 'todolist/:id',   to: 'todolist#update'     ,as: 'update_todolist'

  #todoを削除
  delete 'todo/:id',       to: 'todolist#delete'    ,as: 'tododelete'
  delete 'todolist/:id',   to: 'todolist#listdelete',as: 'listdelete_todolist'

  #todostate(todoを追加)
  get  'todostates/new',    to: 'todostates#new'
  post 'todostates/create', to: 'todostates#create', as: 'add_todo'

  #todoの状況を参照
  get 'todostates/:id',     to: 'todostates#show',as: 'todostate'

  #todoの状況を更新
  patch 'todostates/:id',     to: 'todostates#update', as: 'update_status'

  root 'maps#index'
  get  '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # commentを作成
  get  'comments/new',      to: 'comments#new', as: 'new_comment'
  post 'comments/create',   to: 'comments#create', as: 'create_comment'

  #　commentを参照
  get  'comments/:id',      to: 'comments#show', as: 'comment'

  # commentを更新
  get  'comments/:id/edit', to: 'comments#edit', as: 'edit_comment'
  patch 'comments/:id',     to: 'comments#update', as: 'update_comment'

  # commentを削除
  delete 'comments/:id',    to: 'comments#destroy', as: 'destroy_comment'
end

app/views/shared/_card.html.erb
<div class="card shadow-sm">
  <a href="#" class="link-opacity-75-hover detail-view">
    <div class="row g-0">
      <div class="d-flex card-header p-0">
        <%= image_with_placeholder(todo[:image], todo[:title]) %>
        <div class="d-flex flex-column p-2 flex-fill">
          <h5 class="card-title mb-0"><%= todo[:title] %></h5>
          <p class="card-text author-text"><%= todo[:author] %></p>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text description-text"><%= todo[:description] %></p>
      </div>
    </div>
  </a>
</div>

app/views/shared/_detail.html.erb
    
<div class="slide-sidebar" id="detailSlideSidebar">
  <div class="container p-4">
    <h2 class="mb-4 fs-3">リスト詳細</h2>
    <div class="mb-3">
      <h4 class="h4 fs-5">タイトル</h4>
      <p>名古屋のおすすめレストラン</p>
    </div>
    <div class="mb-3">
      <h4 class="h4 fs-5">ユーザー名</h4>
      <p>ユーザー1</p>
    </div>
    <div class="mb-3">
      <h4 class="h4 fs-5">概要</h4>
      <p>名古屋駅周辺のおすすめのレストランを3個まとめました。</p>
    </div>
    <div class="mb-3">
      <h4 class="h4 fs-5">場所</h4>
      <ul class="list-unstyled">
        <li>ガスト名古屋駅前店</li>
        <li>バーミヤン名古屋駅前店</li>
        <li>マック名古屋駅前店</li>
      </ul>
    </div>
    <div class="mb-3">
      <h4 class="h4 fs-5">写真</h4>
      <div class="row">
        <div class="col-4">
          <img src="https://sakurayama.nagoya/wp-content/uploads/2018/10/img_5769-e1538973165405.jpg" alt="レストラン1" class="img-fluid">
        </div>
        <div class="col-4">
          <img src="https://sakurayama.nagoya/wp-content/uploads/2018/10/img_5769-e1538973165405.jpg" alt="レストラン2" class="img-fluid">
        </div>
        <div class="col-4">
          <img src="https://sakurayama.nagoya/wp-content/uploads/2018/10/img_5769-e1538973165405.jpg" alt="レストラン3" class="img-fluid">
        </div>
      </div>
    </div>
    <button type="button" class="btn btn-primary mt-4">登録</button>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_icons.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
  </symbol>
  <symbol id="home" viewBox="0 0 16 16">
    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
    <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
  </symbol>
  <symbol id="table" viewBox="0 0 16 16">
    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
  </symbol>
  <symbol id="people-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
  </symbol>
</svg>

app/views/shared/_slide.html.erb
<%= render partial: "shared/todo_list", locals: { todos: @todos } %>
<%= render partial: "shared/todo_form" %>
<%= render partial: "shared/todo_detail" %>

app/views/shared/_todo_detail.html.erb
<div class="slide-sidebar position-fixed bg-white z-0" id="detailSlideSidebar">
  <div class="container p-4">
    <h2 id="detail-title" class="fs-3 mb-2">タイトル</h2>
    <p id="detail-author">ユーザー</p>
    <p id="detail-description">名古屋駅周辺のおすすめのレストランを3個まとめました。</p>
    <div id="detail-cards">
      <div id="detail-card-1" class="card" style="width: 18rem;">
        <img src="" class="card-img-top" alt="">
        <div class="card-body">
          <p id="detail" class="card-text">Description</p>
          <a id="like" href="#" class="btn btn-primary">Like</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_todo_form.html.erb
<div class="slide-sidebar position-fixed bg-white <%= 'show' if @form_slide_open %>" id="postSlideSidebar">
  <div class="container p-4">
    <h2 class="fs-3 mb-2">リストの投稿</h1>
    <% if @todo&.errors&.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @todo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: @todo, url: create_todo_path, local: true, html: { multipart: true }) do |f| %>
      <fieldset class="form-group mb-2">
        <%= f.label :title, "タイトル", class: 'form-label' %>
        <%= f.text_field :title, class: 'form-control', placeholder: "タイトル" %>
      </fieldset>
      <fieldset class="form-group mb-2">
        <%= f.label :description, "リストの概要", class: 'form-label' %>
        <%= f.text_area :description, rows: 3, class: 'form-control', placeholder: "例：沖縄県のおすすめのスポットをまとめました。" %>
      </fieldset>
      <h3 class="fs-6">リスト</h3>
      <div id="todo_lists">
        <%= f.fields_for :todo_lists do |todolist_form| %>
          <div class="card mb-2 placeholder-card">
            <div class="card-body">
              <p class="card-text">まだリストが追加されていません。</p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="input-group flex-nowrap mb-3">
        <input type="text" name="query" id="query" placeholder="場所を検索" class="form-control" aria-describedby="addon-wrapping">
        <span id="search-button" class="btn btn-primary input-group-text"><i class="fas fa-search"></i></span>
      </div>
      <%= f.submit "投稿", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div id="search-result" class="position-fixed position-fixed bottom-0 end-0 m-2 p-0 invisible" style="width: 250px;">
  <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-body-tertiary" style="height: 350px">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-body-emphasis text-decoration-none border-bottom justify-content-between">
      <span class="fs-6 fw-semibold">検索結果</span>
      <span id="cross" >
        <i role="button" class="fa-solid fa-xmark"></i>
      </span>
    </div>
    <div id="search-result-list" class="list-group list-group-flush border-bottom scrollarea">
    </div>
  </div>
</div>

app/views/shared/_todo_list.html.erb
<div class="slide-sidebar position-fixed bg-white z-1" id="slideSidebar">
  <div class="container p-4">
    <h2 class="fs-3 mb-2">リスト一覧</h2>
    <div class="input-group flex-nowrap mb-3">
      <input id="searchInput" type="text" class="form-control" placeholder="絞り込み" aria-label="絞り込み" aria-describedby="addon-wrapping">
      <span class="input-group-text" id="addon-wrapping"><i class="fas fa-search"></i></span>
    </div>
    <div class="row" id="resultsContainer">
      <% @todos.each do |todo| %>
        <div id="card-<%= todo[:id] %>" class="col-12 g-2 card-view">
          <%= render partial: "shared/card", locals: {todo: todo} %>
          <% todo[:list].each do |li| %>
            <div id="img-<%= li[:id] %>" data-img-<%= li[:id] %>="<%= CGI.escapeHTML(image_card_with_placeholder(li.image, li[:details])) %>"></div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag "custom/search", defer: true %>
<div>
  <div id="td" data-td-id="<%= @todos.to_json %>"></div>
</div>