config/routes.rb
Rails.application.routes.draw do
  # todo(todolist)を作成
  get  'todolist/new',    to: 'todolist#new',    as: 'new_todolist'
  post 'todolist/create', to: 'todolist#create', as: 'create_todolist'

  #todoを参照
  get 'todolist/:id',     to: 'todolist#todoshow'  ,as: 'todo'
  get 'todolist/users/:id', to: 'todolist#usertodoshow'

  #todoを更新
  get 'todolist/:id/edit',to: 'todolist#edit'
  patch 'todolist/:id',   to: 'todolist#update'     ,as: 'update_todolist'

  #todoを削除
  delete 'todo/:id',       to: 'todolist#delete'    ,as: 'tododelete'
  delete 'todolist/:id',   to: 'todolist#listdelete',as: 'listdelete_todolist'

  #todostate(todoを追加)
  get  'todostates/new',    to: 'todostates#new'
  post 'todostates/create', to: 'todostates#create', as: 'add_todo'

  #todoの状況を参照
  get 'todostates/:id',     to: 'todostates#show',as: 'todostate'

  #todoの状況を更新
  patch 'todostates/:id',     to: 'todostates#update', as: 'update_status'

  root 'maps#index'
  get  '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # commentを作成
  get  'comments/new',      to: 'comments#new', as: 'new_comment'
  post 'comments/create',   to: 'comments#create', as: 'create_comment'

  #　commentを参照
  get  'comments/:id',      to: 'comments#show', as: 'comment'

  # commentを更新
  get  'comments/:id/edit', to: 'comments#edit', as: 'edit_comment'
  patch 'comments/:id',     to: 'comments#update', as: 'update_comment'

  # commentを削除
  delete 'comments/:id',    to: 'comments#destroy', as: 'destroy_comment'
end

app/models/todostate.rb
class Todostate < ApplicationRecord
  belongs_to :user
  belongs_to :todolist
end

app/controllers/todostates_controller.rb
class TodostatesController < ApplicationController
  before_action :require_login, only: %i[new create edit update delete]
  # 新しいTodoStateを作成

  def new
    @todos = Todo.includes(:todo_lists).all
  end

  def create
    todostate_params[:todostates].each do |todostate_param|
      todostate = Todostate.new(todostate_param)

      unless todostate.save
        @todos = Todo.includes(:todo_lists).all
        render :new and return
      end
    end
    redirect_to root_path, notice: 'Todostates were successfully created.'
  end

  # ユーザのステータスの状況を表示
  def show
    # TodoのidとTodolistのTodo_idを結合
    # TodolistsのidとTodostateのTodolist_idを結合し、
    # ユーザに絞る
    @todostate = Todo.joins(todo_lists: :todostates)
                     .where(todostates: { user_id: params[:id] })
                     .select('todos.title, todostates.*,
             todolists.latitude,todolists.longitude')
  end

  # Statusを更新
  def update
    @todostate = Todostate.find_by(todolist_id: params[:id])
    @todostate.status = !@todostate.status # statusを反転させる
    if @todostate.save
      redirect_to todostate_path(@todostate.user_id), notice: 'Status was successfully updated.' # 更新成功時のリダイレクト先
    else
      render :show # 更新失敗時の再表示
    end
  end

  private

  # パラメータ制御
  def todostate_params
    params.require(:todostate).permit(todostates: %i[user_id todolist_id status])
  end

  # ログインが必要
  def require_login
    return if logged_in?

    redirect_to login_path, alert: 'Please log in to continue'
  end
end

app/helpers/todostates_helper.rb
module TodostatesHelper
end

app/views/todostates/new.html.erb
<% @todos.each do |todo| %>
  <%= form_with(model: @todostate, url: add_todo_path, local: true) do |form| %>
    <h3><%= todo.title %></h3>

    <% todo.todo_lists.each do |todolist| %>  
      <%= fields_for "todostate[todostates][]", Todostate.new do |ts_form| %>
        <%= ts_form.hidden_field :user_id, value: current_user.id %>
        <%= ts_form.hidden_field :todolist_id, value: todolist.id %>
        <%= todolist.id%>
        <%= ts_form.hidden_field :status,value:false %>
      <% end %>
    <% end %> 


    <div class="actions">
      <%= form.submit "Create Todostates" %>
    </div>
  <% end %>
<% end %>

app/views/todostates/show.html.erb
<h3>ユーザー名<%= current_user.id %></h3>

<div>
  <table>
    <thead>
      <tr>
        <th>Todo Title</th>
        <th>Todolist_id</th>
        <th>Todo List latitude</th>
        <th>Todo List longitude</th>
        <th>Todostate Status</th>
        <th>Todostate 更新</th>
      </tr>
    </thead>
    <tbody>
      <% @todostate.each do |record| %>
        <tr>
          <td><%= record.title %></td>
          <td><%= record.todolist_id %></td>
          <td><%= record.latitude %></td>
          <td><%= record.longitude %></td>
          <td><%= record.status %></td>
          <td>
            <%= form_with(url: 
            update_status_path(record.todolist_id), method: :patch, local: true) do %>
            <%= submit_tag 'chenge status' %>
            <% end %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }

  th, td {
    border: 1px solid black;
    padding: 8px;
    text-align: left;
  }
</style>