config/routes.rb
Rails.application.routes.draw do
  # todo(todolist)を作成
  get  'todolist/new',    to: 'todolist#new',    as: 'new_todolist'
  post 'todolist/create', to: 'todolist#create', as: 'create_todolist'

  #todoを参照
  get 'todolist/:id',     to: 'todolist#todoshow'  ,as: 'todo'
  get 'todolist/users/:id', to: 'todolist#usertodoshow'

  #todoを更新
  get 'todolist/:id/edit',to: 'todolist#edit'
  patch 'todolist/:id',   to: 'todolist#update'     ,as: 'update_todolist'

  #todoを削除
  delete 'todo/:id',       to: 'todolist#delete'    ,as: 'tododelete'
  delete 'todolist/:id',   to: 'todolist#listdelete',as: 'listdelete_todolist'

  #todostate(todoを追加)
  get  'todostates/new',    to: 'todostates#new'
  post 'todostates/create', to: 'todostates#create', as: 'add_todo'

  #todoの状況を参照
  get 'todostates/:id',     to: 'todostates#show',as: 'todostate'

  #todoの状況を更新
  patch 'todostates/:id',     to: 'todostates#update', as: 'update_status'

  root 'maps#index'
  get  '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # commentを作成
  get  'comments/new',      to: 'comments#new', as: 'new_comment'
  post 'comments/create',   to: 'comments#create', as: 'create_comment'

  #　commentを参照
  get  'comments/:id',      to: 'comments#show', as: 'comment'

  # commentを更新
  get  'comments/:id/edit', to: 'comments#edit', as: 'edit_comment'
  patch 'comments/:id',     to: 'comments#update', as: 'update_comment'

  # commentを削除
  delete 'comments/:id',    to: 'comments#destroy', as: 'destroy_comment'
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  #todoモデルとtodo_listsモデルは1:多
  has_many :todo_lists,class_name: 'Todolist', dependent: :destroy
  #todoモデルの更新とともに、todo_listsも更新
  accepts_nested_attributes_for :todo_lists

  #バリデーションを走らせる前に、Fromの空要素を削除
  before_validation :remove_empty_todo_lists

  #コメントテーブルを複数所持する
  has_many :comments

  validates :title, presence: true
  validates :description, presence: true

  private
  def remove_empty_todo_lists
    todo_lists.each do |todo_list|
      if todo_list.latitude.blank? && todo_list.longitude.blank? && todo_list.details.blank? && todo_list.image.blank?
        todo_list.mark_for_destruction
      end
    end
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :logged_in_user, only: %i[create search]
  require 'http'

  def index
    @todo = Todo.new
    todos = Todo.order(created_at: :desc).limit(20)
    @todos = todos.map { |todo| build_response(todo) }
    @form_slide_open = false
  end

  def create
    @todo = current_user.todos.build(todo_params)
    logger.debug "Todo params: #{todo_params.inspect}"

    # トランザクションで複数の `Todolist` とその画像を保存
    ActiveRecord::Base.transaction do
      if @todo.save
        attach_images_to_todolists
        redirect_to root_path, notice: 'Todo was successfully created.'
      else
        todos = Todo.limit(10)
        @todos = todos.map { |todo| build_response(todo) }
        @form_slide_open = true
        render :index, status: :unprocessable_entity
      end
    end
  rescue StandardError => e
    flash[:error] = "There was an error saving the Todo: #{e.message}"
    redirect_to root_path
  end

  def search
    data = search_places(params[:query])
    render json: data
  end

  private

  def search_places(query)
    api_key = ENV['GMAP_API_KEY']
    url = 'https://places.googleapis.com/v1/places:searchText'

    response = HTTP.post(
      url,
      headers: { 'Content-Type' => 'application/json',
                 'X-Goog-Api-Key': api_key,
                 'X-Goog-FieldMask': 'places.displayName,places.formattedAddress,places.location' },
      body: { textQuery: query, pageSize: 10, languageCode: 'ja', locationRestriction: {
        rectangle: {
          low: { latitude: 24.396308, longitude: 122.934570 },
          high: { latitude: 45.551483, longitude: 153.986672 }
        }
      } }.to_json
    )

    if response.status.success?
      JSON.parse(response.body.to_s)['places']
    else
      []
    end
  end

  def build_response(todo)
    {
      id: todo.id,
      title: todo.title,
      description: todo.description,
      author: todo.user.name,
      image: todo.todo_lists.first&.image || nil,
      list: todo.todo_lists
    }
  end

  def attach_images_to_todolists
    params[:todo][:todo_lists_attributes].each do |_index, todolist_params|
      next unless todolist_params[:image].present?

      todolist = @todo.todo_lists.find_by(id: todolist_params[:id])
      if todolist
        logger.debug "Attaching image to Todolist: #{todolist.inspect}"
        todolist.image.attach(todolist_params[:image])
      else
        flash[:error] = 'Todolist not found for attaching image.'
      end
    end
  end

  def todo_params
    params.require(:todo).permit(:title, :description,
                                 todo_lists_attributes: %i[id latitude longitude details _destroy image])
  end
end

app/views/todos/index.html.erb
<%= render 'shared/icons' %>
<main class="d-flex flex-nowrap">
  <nav class="d-flex flex-column flex-shrink-0 p-3 z-3 bg-white" style="box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none">
      <span class="fs-5">Journey Junction</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link" id="listToggle">
          <i class="fa-solid fa-list me-2"></i>
          リスト一覧
        </a>
      </li>
      <% if logged_in? %>
        <li class="nav-item post-list-toggle">
          <a href="#" class="nav-link" id="listToggle">
            <i class="fa-solid fa-comment me-2"></i>
            リストの投稿
          </a>
        </li>
        <li class="nav-item post-list-toggle">
          <a href="#" class="nav-link" id="listToggle">
            <i class="fa-solid fa-star me-2"></i>
            お気に入り
          </a>
        </li>
      <% end %>
    </ul>
    <%# <%= debug(params) if Rails.env.development? %>
    <hr>
    <% if logged_in? %>
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <%= gravatar_for current_user, size: 32 %>
          <strong><%= current_user.name %></strong>
        </a>
        <ul class="dropdown-menu text-small shadow">
          <li><a class="dropdown-item post-list-toggle" href="#">リストの投稿</a></li>
          <li><a class="dropdown-item" href="#">設定</a></li>
          <li><a class="dropdown-item" href="#">プロフィール</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to "ログアウト", logout_path, class: "dropdown-item", data: { "turbo-method": :delete } %></li>
        </ul>
      </div>
    <% else %>
      <%= link_to "ログイン", login_path, class: "btn btn-primary" %>
    <% end %>
  </nav>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
  <div id="map"></div>
  <script>
    (g => {
      var h, a, k, p = "The Google Maps JavaScript API", c = "google", l = "importLibrary", q = "__ib__", m = document, b = window;
      b = b[c] || (b[c] = {});
      var d = b.maps || (b.maps = {}), r = new Set, e = new URLSearchParams, u = () => h || (h = new Promise(async (f, n) => {
        await (a = m.createElement("script"));
        e.set("libraries", [...r] + "");
        for (k in g) e.set(k.replace(/[A-Z]/g, t => "_" + t[0].toLowerCase()), g[k]);
        e.set("callback", c + ".maps." + q);
        a.src = `https://maps.${c}apis.com/maps/api/js?` + e;
        d[q] = f;
        a.onerror = () => h = n(Error(p + " could not load."));
        a.nonce = m.querySelector("script[nonce]")?.nonce || "";
        m.head.append(a)
      }));
      d[l] ? console.warn(p + " only loads once. Ignoring:", g) : d[l] = (f, ...n) => r.add(f) && u().then(() => d[l](f, ...n))
    })({
      key: "<%= ENV["GMAP_API_KEY"] %>", v: "beta"
    });
  </script>
</main>
<%= javascript_include_tag "custom/map", :defer => "defer" %>
<%= javascript_include_tag "custom/sidebar", :defer => "defer" %>
<%= render partial: "shared/slide", locals: { todos: @todos } %>